export const Images = () => {
  return [
   {src: "https://nohaypuntadasinhilo.com/images/rough/img1.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img2.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img3.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img4.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img5.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img6.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img7.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img8.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img9.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img10.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img11.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img12.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img13.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img14.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img15.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img16.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img17.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img18.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img19.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img20.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img21.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img22.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img23.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img24.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img25.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img26.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img27.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img28.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img29.jpg"},
   {src: "https://nohaypuntadasinhilo.com/images/rough/img30.jpg"}
  ];
}